# Generated by Django 2.2.7 on 2019-11-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='description',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
